# Numpy Exercises

Import NumPy as np

In [2]:
import numpy as np

Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 zeros

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 fives

In [6]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [28]:
a=np.identity(3)

In [29]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([0.15021395])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal
distribution

In [13]:
np.random.randn(25)

array([-1.37681998,  0.14770633,  0.14049809, -0.63167829, -1.8124446 ,
        0.25557127,  0.45594554,  0.78747998,  0.70809272, -0.70522692,
       -0.87225   , -2.01420498,  1.17083745, -1.07822965, -1.17590012,
        1.48603399,  0.648426  , -0.87980202, -0.00819869,  0.00337425,
        1.16909359, -0.44372856, -1.21869211,  0.14597564,  0.87366482])

Create an array of 20 linearly spaced points between 0 and 1

In [14]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [24]:
mat[3][4]

20

In [25]:
mat[0:5,1].reshape(5,1)

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [26]:
mat[4]

array([21, 22, 23, 24, 25])

In [27]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Create the following matrix:

In [30]:
np.random.rand(3,3)

array([[0.20796577, 0.22944057, 0.8402815 ],
       [0.01697382, 0.41712733, 0.85906069],
       [0.57268956, 0.41371683, 0.14349615]])